### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by gruossomonica** [lhoyer/improving_segmentation_with_selfsupervised_depth#1]
Hi, 
thank you for your interesting work. 
I'm interested in semi-supervised segmentation. I have a question. Can I perform training using your approach with my own dataset? I collected about 5k images with binary segmentation masks (foreground and background classes). What are the tips and steps in this case?
I look forward to your reply. Thank you.

Best Regards,

Monica

**Comment by lhoyer** [comment]
Thank you for your interest in our work. To apply our method, your dataset has to fulfill the following criteria:
* there is access to the underlying video clips in order to train SDE,
* some of the images from the video clips have segmentation labels, and
* the camera intrinsics have to be known.

If that is the case, you can check out the class CityscapesLoader in [loader/cityscapes_loader.py](https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/master/loader/cityscapes_loader.py#L112) for a reference on how to implement your own data loader. It inherits from [loader/sequence_segmentation_loader.py](https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/master/loader/sequence_segmentation_loader.py), where you can find out more about the underlying data loading logic. In order to adapt the framework to the new data loader, a search with the keyword "cityscapes" will reveal the relevant places. After that, the [README.md](https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/master/README.md) will guide you through the training process.

**Comment by gruossomonica** [comment]
Thanks for the detailed explanation.

Best Regards, 

Monica

**Comment by AnukritiSinghh** [comment]
Hey @gruossomonica, were you able to run EXP 210 or 211? how did you place your dataset in the folders? 
Thank you

**Comment by gruossomonica** [comment]
Hi @AnukritiSinghh! Sorry, I didn't try because I didn't have the information about the camera intrinsics and more than one camera was used to collect my dataset. 

Best regards.

**Comment by fjremnav** [comment]
@gruossomonica 

   Have you succeeded to modify the codes for your own datasets?

Thanks,
