### ISSUE TITLE
Clarification regarding the semi supervised segmentation task

### ISSUE THREAD

**Issue by testingshanu** [lhoyer/improving_segmentation_with_selfsupervised_depth#7]
1. Which experiment id is suitable to train the semantic segmentation network using all the labels from cityscape ? (while using the monodepth pretrained model)

2. Is "leftImg8bit_sequence_small" data required  while running only the semi supervised segmentation experiments ?

**Comment by lhoyer** [comment]
1. You can achieve that by enabling 2975 samples and disabling 372 samples in the [subsets function in experiments.py](https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/1a6f4a88863602807d4192072ce5527c97a5b213/experiments.py#L112). Further, you should comment our ["(f'sel_{pres_method}_pad_transfer_dcompgt{dc_m}{dc_ft}', True, "depthcomp", False, True, True)" in experiments.py](https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/1a6f4a88863602807d4192072ce5527c97a5b213/experiments.py#L345). After that, you can run `python run_experiments.py --machine ws --exp 212`. If you run into memory issues, please consider issue #4.
2. Yes, the sequences are also required for the fully supervised case due to the MTL with self-supervised depth.

**Comment by testingshanu** [comment]
Thank you for the reply.

What does MTL indicate ?

**Comment by lhoyer** [comment]
MTL=Multi-Task Learning
